name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pyconll
        pip install numpy
        pip install pandas
    - name: Analysing the code with pylint
      run: |
        pylint  --exit-zero `ls|grep .py$|xargs`
        pylint  --exit-zero gaelic_pos
        pylint  --exit-zero innealan
